version: '3.0'

services:
  
  calendar:
    environment:
       - NODE_ENV=production 
    network_mode: host
    command: "npm run start"

  auth: 
    environment:
       - NODE_ENV=production
    network_mode: host
    command: "npm run start"

  gateway:
    environment:
       - NODE_ENV=production
    expose:
       - '3000'
    network_mode: host
    depends_on:
       - auth
       - calendar
    command: "npm run start"
