version: '3.0'

services:

  redis-server:
    network_mode: host
  
  calendar:
    environment:
       - NODE_ENV=production 
    network_mode: host
    depends_on:
       - redis-server
    command: "npm run start:prod"

  auth: 
    environment:
       - NODE_ENV=production
    network_mode: host
    depends_on:
      - redis-server
    command: "npm run start:prod"

  gateway:
    environment:
       - NODE_ENV=production
    expose:
       - '3000'
    network_mode: host
    depends_on:
       - auth
       - calendar
       - redis-server
    command: "npm run start:prod"
