version: '3.0'

services:

  redis-server:
   build :
     context: .
     dockerfile: ./redis/.
   container_name: redis-service
   restart: on-failure 
  
  calendar:
   build:
     context: .
     dockerfile: ./calendar/.
   container_name: calendar_service
   restart: on-failure

  auth:
   build:
     context: .
     dockerfile: ./auth/.  
   container_name: auth_service
   restart: on-failure

  gateway:
   build:
     context: .
     dockerfile: ./gateway/.
   container_name: gateway_service
   restart: on-failure