version: '3.0'

services:

  redis-server:
   build :
      context: .
      dockerfile: ./redis/.
    container_name: redis-service
    restart: on-failure 
   network_mode: host
  
  calendar:
    environment:
       - NODE_ENV=development
    network_mode: host
    depends_on:
       - redis-server
    command: "npm run start:dev"

  auth: 
    environment:
       - NODE_ENV=development
    network_mode: host
    depends_on:
      - redis-server
    command: "npm run start:dev"

  gateway:
    environment:
       - NODE_ENV=development
    expose:
       - '3000'
    network_mode: host
    depends_on:
       - auth
       - calendar
       - redis-server
    command: "npm run start:dev"
