server :
  #URL : 'redis://localhost:6379'
   URL : 'redis://redis-server:6378'

database :
  type : 'postgres'
  username : 'postgres' 
  password : 'root'
  host: 'localhost'
  database : 'auth'
  port : 5432
  synchronize : false

JWT :
  expiresIn : 36000000
  secret : 'topSecret51'
  defaultStrategy : 'jwt'

textLocal :
  APIKey : 'ZykcD17gN0A-7D7kZfoBD4Xf9RZFG5v3shNk28WVDw'
  sender: 'TXTLCL'
