export const CONSTANT_MSG = {
    AUTH  : "Auth",
    CALENDER :  'Calender',
    CHAT : 'Chat',
    SERVICE_INACTIVE_MSG : 'service is offline. Please check once',
    SERVICE_ACTIVE_MSG : 'service is online',
    INVALID_CREDENTIALS: 'Invalid Credentails',
    DB_ERROR: 'Error in Database Query',
    CONTENT_NOT_AVAILABLE: 'Content Not Available',
    INVALID_MOBILE_NO: 'Invalid mobile Number',
    UPDATE_FAILED: "Updation Failed",
    UPDATE_OK:"Updated Successfully",
    APPOINT_CANCELED: 'Appointment Cancelled Successfully',
    DAY_OF_WEEK:'Please enter DayOfWeek Correctly',
    ALREADY_PRESENT:'User already present.Do login',
    INVALID_REQUEST:'Invalid request',
    PHONE_EXISTS:"Phone number already exists",
    TIME_OVERLAP:'Time Overlapping with previous Time Interval',
    APPOINT_ALREADY_CANCELLED:'Appointment already Cancelled',
    CONFIRMATION_REQUIRED:'Confirmation Required',
    NO_PERMISSION:'No Permission',
    INVALID_PHONE:'Invalid Phone',
    INVALID_PASSWORD:'Invalid Password',
    END_TIME_MISMATCHING:'End time is mismatching with respect to doctor session timing',
    INVALID_TIMINGS:'start time should be less than endTime',
    NO_WORK_SCHEDULE:'Doctor has no workSchedule on this Date',
    ROLES:{
        DOCTOR:'DOCTOR',
        ADMIN:'ADMIN',
        DOC_ASSISTANT:'DOC_ASSISTANT',
        PATIENT:'PATIENT'
    }
}