server:
  port : 3000

openVidu:
  urlOpenViduServer : "https://dev.virujh.com/dashboard"
  secret : "Virujh123"

JWT :
  expiresIn : 36000000
  secret : 'topSecret51'
  defaultStrategy : 'jwt'

redis : 
  host: 'localhost'
  port: 6379