server:
  port : 3000
openVidu:
  urlOpenViduServer : "https://devideo.virujh.com/dashboard"
  secret : "Virujh#123"

JWT :
  expiresIn : 36000000
  secret : 'topSecret51'
  defaultStrategy : 'jwt'

redis : 
  host: 'dev-redis-gateway.ysl6gq.ng.0001.aps1.cache.amazonaws.com'
  port: 6379