server:
  port : 8081

openVidu:
  urlOpenViduServer : "https://devideo.virujh.com/dashboard"
  secret : "Virujh#123"

JWT :
  expiresIn : 36000000
  secret : 'topSecret51'
  defaultStrategy : 'jwt'

redis : 
  host: 'virujhliveredis-001.ysl6gq.0001.aps1.cache.amazonaws.com'
  port: 6379