server :
#  URL : 'redis://localhost:6379'
 URL : 'redis://redis-loc-server:6379'

database :
  type : 'postgres'
  username : 'postgres'
  password : 'postgres'
  host: 'db_calendar'
  database : 'livecalendar'
  port : 5432
  synchronize : false

openVidu:
  urlOpenViduServer: "https://devideo.virujh.com/dashboard"
  secret: "Virujh#123"
