server :
  URL : 'redis://localhost:6379'

database :
  type : 'postgres'
  username : 'postgres'
  password : 'postgres'
  host: 'virujh-dev-new.cjxvyzcwczxh.ap-south-1.rds.amazonaws.com'
  database : 'livecalendar'
  port : 5432
  synchronize : false
