server :
#  URL : 'redis://localhost:6379'
 URL : 'redis://redis-server:6378'

database :
  type : 'postgres'
  username : 'postgres'
  password : 'postgres'
  host: 'virujh-dev-new.cjxvyzcwczxh.ap-south-1.rds.amazonaws.com'
  database : 'calendar'
  port : 5432
  synchronize : false

openVidu:
  urlOpenViduServer: "https://devideo.virujh.com/dashboard"
  secret : "Virujh#123"
