server :
  URL : 'redis://localhost:6379'
  #URL : 'redis://redis-loc-server:6379'

database :
  type : 'postgres'
  username : 'postgres'
  password : 'root'
  host: 'localhost'
  database : 'calendar'
  port : 5432
  synchronize : false

openVidu:
  urlOpenViduServer: "https://dev.virujh.com/dashboard"
  secret : "Virujh123"
