server :
  URL : 'redis://localhost:6379'

database :
  type : 'postgres'
  username : 'postgres'
  password : 'root'
  host: 'localhost'
  database : 'calendar'
  port : 5432
  synchronize : false

openVidu:
  urlOpenViduServer : "https://devideo.virujh.com/dashboard"
  secret : "Virujh#123"
  