server :
  URL : 'redis://virujhliveredis-001.ysl6gq.0001.aps1.cache.amazonaws.com:6379'

database :
  type : 'postgres'
  username: 'postgres'
  password: 'postgres'
  host: 'virujh-dev-new.cjxvyzcwczxh.ap-south-1.rds.amazonaws.com'
  database : 'calendar'
  port : 5432
  synchronize : false

openVidu:
  urlOpenViduServer: "https://devideo.virujh.com/dashboard"
  secret: "Virujh#123"
  